//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterBot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gZG9lasfDFwX6eVlm2caaKDiL")]
        public string customer_key {
            get {
                return ((string)(this["customer_key"]));
            }
            set {
                this["customer_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fjYbDHQuQdO01vilKZqjo7hlr1xRQnBMqPLjD6O7J7YT9VYqRR")]
        public string customer_key_secret {
            get {
                return ((string)(this["customer_key_secret"]));
            }
            set {
                this["customer_key_secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("885177134247026688-PU0JKekt5mepf43MibWjyK1PGWkN9V8")]
        public string access_token {
            get {
                return ((string)(this["access_token"]));
            }
            set {
                this["access_token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F5hSvp10QmBpUHC4Qm1GPmbBdinubi0FrS1KpugUarD49")]
        public string access_token_secret {
            get {
                return ((string)(this["access_token_secret"]));
            }
            set {
                this["access_token_secret"] = value;
            }
        }
    }
}
